name: silvercart
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.7.2

dependencies: 
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  retrofit:
  json_annotation:
  connectivity_plus: ^6.0.3
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  get: 4.7.2
  # QR Code functionality
  qr_flutter: ^4.1.0
  # qr_code_scanner:
  # Image picker
  image_picker:
  # Share functionality
  share_plus:
  get_it:
  flutter_dotenv:
  shared_preferences:
  http:
  flutter: 
    sdk: flutter
  google_speech: ^5.3.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1
  agora_rtc_engine: ^6.5.2
  path_provider: ^2.1.5
  device_info_plus: ^11.5.0

dev_dependencies: 
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  json_serializable:
  retrofit_generator: ^9.1.5
  injectable:
  injectable_generator: ^2.6.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - .env

